#!/usr/bin/env python

import rospy
from sensor_msgs.msg import BatteryState
from geometry_msgs.msg import Point, Quaternion
from geometry_msgs.msg import PoseStamped
from nav_msgs.msg import Odometry
import gobject
from ble_interface import GattServer
from ble_interface import BleAdvertisement
import dbus

class RobotAdvertisement(BleAdvertisement.Advertisement):

    def __init__(self, bus, index):
        super(RobotAdvertisement, self).__init__(bus, index, 'peripheral')
        self.add_service_uuid('180F') # 180F - Battery Service
        self.add_service_uuid('c2ad5ff9-f58c-4c72-9f01-7c5b3ee1f595') # Odometry service
        self.include_tx_power = True

# The Battery service
class BatteryService(GattServer.Service):
    BATTERY_UUID = '180f'

    def __init__(self, bus, index):
        super(BatteryService, self).__init__(bus, index, self.BATTERY_UUID, True)
        self.add_characteristic(BatteryLevelCharacteristic(bus, 0, self))


class BatteryLevelCharacteristic(GattServer.Characteristic):
    BATTERY_LVL_UUID = '2a19'

    def __init__(self, bus, index, service):
        super(BatteryLevelCharacteristic, self).__init__(
                bus, index,
                self.BATTERY_LVL_UUID,
                ['read', 'notify'],
                service)
        self.notifying = False
        self.battery_lvl = 100

    def notify_battery_level(self):
        if not self.notifying:
            return
        self.PropertiesChanged(
                GattServer.GATT_CHRC_IFACE,
                { 'Value': [dbus.Byte(self.battery_lvl)] }, [])

    def level_cb(self, data):
        int_percentage = int(data.percentage)
        if self.battery_lvl != int_percentage:
            rospy.logdebug('Updated battery level to %d', int_percentage)
            self.battery_lvl = int_percentage
            self.notify_battery_level()
        return

    def ReadValue(self):
        rospy.logdebug('Battery Level read: ' + repr(self.battery_lvl))
        return [dbus.Byte(self.battery_lvl)]

    def StartNotify(self):
        if self.notifying:
            rospy.logdebug('Already notifying, nothing to do')
            return

        self.notifying = True
        self.notify_battery_level()

    def StopNotify(self):
        if not self.notifying:
            rospy.logdebug('Not notifying, nothing to do')
            return

        self.notifying = False

# The Odometry service
class OdometryService(GattServer.Service):
    ODOMETRY_UUID = 'c2ad5ff9-f58c-4c72-9f01-7c5b3ee1f595'

    def __init__(self, bus, index):
        super(OdometryService, self).__init__(bus, index, self.ODOMETRY_UUID, True)
        self.add_characteristic(BasePositionCharacteristic(bus, 0, self))
        self.add_characteristic(BaseOrientationCharacteristic(bus, 1, self))
        # self.add_characteristic(BaseLinearVelocityCharacteristic(bus, 2, self))
        # self.add_characteristic(BaseAngularVelocityCharacteristic(bus, 3, self))

class BasePositionCharacteristic(GattServer.Characteristic):
    BASE_POSITION_UUID = 'b2c1fa1e-0757-4bff-89e3-b2d379ed0d91'

    def __init__(self, bus, index, service):
        super(BasePositionCharacteristic, self).__init__(
            bus, index,
            self.BASE_POSITION_UUID,
            ['read', 'notify'],
            service)
        self.notifying = False
        self.position = Point(0,0,0)
        self.add_descriptor(
            GattServer.CharacteristicUserDescriptionDescriptor(
                bus, 
                1, 
                self,
                'Robot Position'))

    def notify_position(self):
        if not self.notifying:
            return
        x = int(self.position.x*1000)
        y = int(self.position.y*1000)
        z = int(self.position.z*1000)
        arr = bytearray.fromhex('{:08x}{:08x}{:08x}'.format(x,y,z))
        self.PropertiesChanged(
            GattServer.GATT_CHRC_IFACE,
            { 'Value': dbus.Array(arr, 'y') }, [])

    def position_cb(self, data):
        if self.position != data.pose.pose.position:
            self.position = data.pose.pose.position
            rospy.logdebug('Updated position: ' + repr(self.position))
            self.notify_position()
        return

    def ReadValue(self):
        rospy.logdebug('Position read: ' + repr(self.position))
        return [[dbus.Double(self.position.x),
                 dbus.Double(self.position.y),
                 dbus.Double(self.position.z)]]

    def StartNotify(self):
        if self.notifying:
            rospy.logdebug('Already notifying, nothing to do')
            return

        self.notifying = True
        self.notify_position()

    def StopNotify(self):
        if not self.notifying:
            rospy.logdebug('Not notifying, nothing to do')
            return

        self.notifying = False

class BaseOrientationCharacteristic(GattServer.Characteristic):
    BASE_ORIENTATION_UUID = '6f805177-4e54-4bd6-9670-5591c2912875'

    def __init__(self, bus, index, service):
        super(BaseOrientationCharacteristic, self).__init__(
                bus, index,
                self.BASE_ORIENTATION_UUID,
                ['read', 'notify'],
                service)
        self.notifying = False
        self.orientation = Quaternion(1,0,0,0)
        self.add_descriptor(
            GattServer.CharacteristicUserDescriptionDescriptor(
                bus, 
                1, 
                self,
                'Robot Orientation'))

    def notify_orientation(self):
        if not self.notifying:
            return
        x = int(self.orientation.x * 1000000000)
        y = int(self.orientation.y * 1000000000)
        z = int(self.orientation.z * 1000000000)
        w = int(self.orientation.w * 1000000000)
        arr = bytearray.fromhex('{:08x}{:08x}{:08x}{:08x}'.format(x,y,z,w))
        self.PropertiesChanged(
            GattServer.GATT_CHRC_IFACE,
            { 'Value': dbus.Array(arr, 'y') }, [])
 

    def orientation_cb(self, data):
        if self.orientation != data.pose.pose.orientation:
            self.orientation = data.pose.pose.orientation
            rospy.logdebug('Updated orientation: ' + repr(self.orientation))
            self.notify_orientation()
        return

    def ReadValue(self):
        rospy.logdebug('Orientation read: ' + repr(self.orientation))
        return [[dbus.Double(self.orientation.x),
                 dbus.Double(self.orientation.y),
                 dbus.Double(self.orientation.z),
                 dbus.Double(self.orientation.w)]]

    def StartNotify(self):
        if self.notifying:
            rospy.logdebug('Already notifying, nothing to do')
            return

        self.notifying = True
        self.notify_orientation()

    def StopNotify(self):
        if not self.notifying:
            rospy.logdebug('Not notifying, nothing to do')
            return

        self.notifying = False

def register_service_cb():
    rospy.logdebug('GATT service registered')

def register_service_error_cb(error):
    rospy.logerr('Failed to register service: ' + str(error))
    rospy.signal_shutdown('Could not start Bluetooth service.')

def register_ad_cb():
    rospy.logdebug('Advertisement registered')

def register_ad_error_cb(error):
    rospy.logerr('Failed to register advertisement: ' + str(error))
    rospy.signal_shutdown('Could not advertise Bluetooth service.')

def main():
    mainloop = gobject.MainLoop()
    gobject.threads_init()
    rospy.on_shutdown(mainloop.quit)
    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

    bus = dbus.SystemBus()

    # Advertize services
    adapter = BleAdvertisement.find_adapter(bus)
    if not adapter:
        rospy.logerr('LEAdvertisingManager1 interface not found')
        return
    adapter_props = dbus.Interface(bus.get_object(BleAdvertisement.BLUEZ_SERVICE_NAME, adapter),
                                   "org.freedesktop.DBus.Properties");
    adapter_props.Set("org.bluez.Adapter1", "Powered", dbus.Boolean(1))
    ad_manager = dbus.Interface(bus.get_object(BleAdvertisement.BLUEZ_SERVICE_NAME, adapter),
                                BleAdvertisement.LE_ADVERTISING_MANAGER_IFACE)
    robot_advertisement = RobotAdvertisement(bus, 0)
    ad_manager.RegisterAdvertisement(robot_advertisement.get_path(), {},
                                     reply_handler=register_ad_cb,
                                     error_handler=register_ad_error_cb)

    # Service
    service_manager = dbus.Interface(
            bus.get_object(GattServer.BLUEZ_SERVICE_NAME, adapter),
            GattServer.GATT_MANAGER_IFACE)
    bat_service = BatteryService(bus, 1)
    service_manager.RegisterService(bat_service.get_path(), {},
                                    reply_handler=register_service_cb,
                                    error_handler=register_service_error_cb)

    odom_service = OdometryService(bus, 2)
    service_manager.RegisterService(odom_service.get_path(), {},
                                    reply_handler=register_service_cb,
                                    error_handler=register_service_error_cb)

    rospy.init_node('ble_interface_battery', log_level=rospy.INFO)
    laptop_charge_sub = rospy.Subscriber('/laptop_charge', BatteryState, bat_service.characteristics[0].level_cb)
    odometry_sub = rospy.Subscriber('/odom', Odometry, odom_service.characteristics[0].position_cb)
    odometry_sub.impl.add_callback(odom_service.characteristics[1].orientation_cb, None)

    mainloop.run()

if __name__ == '__main__':
    main()