#!/usr/bin/env python

import rospy
from std_msgs.msg import Float32
from std_srvs.srv import SetBool, SetBoolResponse
from sensor_msgs.msg import BatteryState
from geometry_msgs.msg import Point, Quaternion
from geometry_msgs.msg import PoseStamped
from nav_msgs.msg import Odometry
from people_msgs.msg import PositionMeasurement, PositionMeasurementArray
import gobject
from ble_interface import GattServer
from ble_interface import BleAdvertisement
import dbus
from math import sqrt, atan2, pi

class RobotAdvertisement(BleAdvertisement.Advertisement):

    def __init__(self, bus, index):
        super(RobotAdvertisement, self).__init__(bus, index, 'peripheral')
        # self.add_service_uuid('180F') # 180F - Battery Service
        # self.add_service_uuid('c2ad5ff9-f58c-4c72-9f01-7c5b3ee1f595') # Odometry service
        # self.add_service_uuid('12345678-1234-5678-1234-56789abcdef0')
        self.include_tx_power = True

# The Battery service
class BatteryService(GattServer.Service):
    BATTERY_UUID = '180f'

    def __init__(self, bus, index):
        super(BatteryService, self).__init__(bus, index, self.BATTERY_UUID, True)
        self.add_characteristic(BatteryLevelCharacteristic(bus, 0, self))


class BatteryLevelCharacteristic(GattServer.Characteristic):
    BATTERY_LVL_UUID = '2a19'

    def __init__(self, bus, index, service):
        super(BatteryLevelCharacteristic, self).__init__(
                bus, index,
                self.BATTERY_LVL_UUID,
                ['read', 'notify'],
                service)
        self.notifying = False
        self.battery_lvl = 100

    def notify_battery_level(self):
        if not self.notifying:
            return
        self.PropertiesChanged(
                GattServer.GATT_CHRC_IFACE,
                { 'Value': [dbus.Byte(self.battery_lvl)] }, [])

    def level_cb(self, data):
        int_percentage = int(data.percentage)
        if self.battery_lvl != int_percentage:
            rospy.logdebug('Updated battery level to %d', int_percentage)
            self.battery_lvl = int_percentage
            self.notify_battery_level()
        return

    def ReadValue(self):
        rospy.logdebug('Battery Level read: ' + repr(self.battery_lvl))
        return [dbus.Byte(self.battery_lvl)]

    def StartNotify(self):
        if self.notifying:
            rospy.logdebug('Already notifying, nothing to do')
            return

        self.notifying = True
        self.notify_battery_level()

    def StopNotify(self):
        if not self.notifying:
            rospy.logdebug('Not notifying, nothing to do')
            return

        self.notifying = False

# The Odometry service
class OdometryService(GattServer.Service):
    ODOMETRY_UUID = 'c2ad5ff9-f58c-4c72-9f01-7c5b3ee1f595'

    def __init__(self, bus, index):
        super(OdometryService, self).__init__(bus, index, self.ODOMETRY_UUID, True)
        self.add_characteristic(BasePositionCharacteristic(bus, 0, self))
        self.add_characteristic(BaseOrientationCharacteristic(bus, 1, self))
        # self.add_characteristic(BaseLinearVelocityCharacteristic(bus, 2, self))
        # self.add_characteristic(BaseAngularVelocityCharacteristic(bus, 3, self))

class BasePositionCharacteristic(GattServer.Characteristic):
    BASE_POSITION_UUID = 'b2c1fa1e-0757-4bff-89e3-b2d379ed0d91'

    def __init__(self, bus, index, service):
        super(BasePositionCharacteristic, self).__init__(
            bus, index,
            self.BASE_POSITION_UUID,
            ['read', 'notify'],
            service)
        self.notifying = False
        self.position = Point(0,0,0)
        self._value_initialized = False
        self.add_descriptor(
            GattServer.CharacteristicUserDescriptionDescriptor(
                bus, 1, self, 'Robot Position'))

    def position_to_bytelist(self):
        x = int(self.position.x*1000)
        x = bytelist_from_int(x, 4)
        y = int(self.position.y*1000)
        y = bytelist_from_int(y, 4)
        z = int(self.position.z*1000)
        z = bytelist_from_int(z, 4)
        return x+y+z

    def notify_position(self):
        if not self.notifying:
            return
        bl = self.position_to_bytelist()
        self.PropertiesChanged(
            GattServer.GATT_CHRC_IFACE,
            { 'Value': dbus.Array(bl, 'y') }, [])

    def position_cb(self, data):
        if self.position != data.pose.pose.position:
            self.position = data.pose.pose.position
            rospy.logdebug('Updated position: ' + repr(self.position))
            self.notify_position()
        return

    def ReadValue(self):
        if not self._value_initialized:
            self._value_initialized = True
            bl = self.position_to_bytelist()
            self.PropertiesChanged(
                GattServer.GATT_CHRC_IFACE,
                { 'Value': dbus.Array(bl, 'y') }, [])
        rospy.logdebug('Position read: ' + repr(self.position))
        return dbus.Array(self.position_to_bytelist(), signature='y')

    def StartNotify(self):
        if self.notifying:
            rospy.logdebug('Already notifying, nothing to do')
            return

        self.notifying = True
        self.notify_position()

    def StopNotify(self):
        if not self.notifying:
            rospy.logdebug('Not notifying, nothing to do')
            return

        self.notifying = False

class BaseOrientationCharacteristic(GattServer.Characteristic):
    BASE_ORIENTATION_UUID = '6f805177-4e54-4bd6-9670-5591c2912875'

    def __init__(self, bus, index, service):
        super(BaseOrientationCharacteristic, self).__init__(
                bus, index,
                self.BASE_ORIENTATION_UUID,
                ['read', 'notify'],
                service)
        self.notifying = False
        self.orientation = Quaternion(1,0,0,0)
        self.add_descriptor(
            GattServer.CharacteristicUserDescriptionDescriptor(
                bus,
                1,
                self,
                'Robot Orientation'))

    def orientation_to_bytelist(self):
        x = int(self.orientation.x * 1000000000)
        x = bytelist_from_int(x, 4)
        y = int(self.orientation.y * 1000000000)
        y = bytelist_from_int(y, 4)
        z = int(self.orientation.z * 1000000000)
        z = bytelist_from_int(z, 4)
        w = int(self.orientation.w * 1000000000)
        w = bytelist_from_int(w, 4)
        return x+y+z+w

    def notify_orientation(self):
        if not self.notifying:
            return
        bl = self.orientation_to_bytelist()
        self.PropertiesChanged(
            GattServer.GATT_CHRC_IFACE,
            { 'Value': dbus.Array(bl, 'y') }, [])


    def orientation_cb(self, data):
        if self.orientation != data.pose.pose.orientation:
            self.orientation = data.pose.pose.orientation
            rospy.logdebug('Updated orientation: ' + repr(self.orientation))
            self.notify_orientation()
        return

    def ReadValue(self):
        rospy.logdebug('Orientation read: ' + repr(self.orientation))
        return dbus.Array(self.orientation_to_bytelist(), signature='y')

    def StartNotify(self):
        if self.notifying:
            rospy.logdebug('Already notifying, nothing to do')
            return

        self.notifying = True
        self.notify_orientation()

    def StopNotify(self):
        if not self.notifying:
            rospy.logdebug('Not notifying, nothing to do')
            return

        self.notifying = False

# The People service
class PeopleService(GattServer.Service):
    PEOPLE_UUID = 'd3b06ab8-8a3c-40ca-bb06-5c3623650896'

    def __init__(self, bus, index):
        super(PeopleService, self).__init__(bus, index, self.PEOPLE_UUID, True)
        self.people_array = PositionMeasurementArray()
        self.current_person = PositionMeasurement()
        self.current_person_valid = False
        self.person_position_characteristic = PersonPositionCharacteristic(
            bus, 0, self)
        self.add_characteristic(self.person_position_characteristic)

    def person_position_array_cb(self, data):
        self.people_array = data
        try:
            self.current_person = next(
                p for p in self.people_array.people if p.name == self.current_person.name)
            self.person_position_characteristic.notify_person_position()
            self.current_person_valid = True
        except StopIteration:
            self.current_person_valid = False
        return

class PersonPositionCharacteristic(GattServer.Characteristic):
    PERSON_POSITION_UUID = 'b52fffd8-88eb-4baa-9e99-88aafdf89480'

    def __init__(self, bus, index, service):
        super(PersonPositionCharacteristic, self).__init__(
            bus, index, self.PERSON_POSITION_UUID, ['read', 'notify'], service)
        self.notifying = False
        self.service = service
        self.add_descriptor(
            GattServer.CharacteristicUserDescriptionDescriptor(
                bus, 1, self, 'Relative Position of Person'))

    def point_to_polar_bytelist(self):
        position = self.service.current_person.position
        dist = sqrt(position.x**2 + position.y**2)
        dist = int(dist * 100)
        dist = bytelist_from_int(dist, 2)
        angle = atan2(position.y, position.y) * 180 / pi
        angle = int(angle * 100)
        angle = bytelist_from_int(angle, 2)
        return dist + angle

    def notify_person_position(self):
        if self.notifying:
            bl = self.point_to_polar_bytelist()
            self.PropertiesChanged(
                GattServer.GATT_CHRC_IFACE, {'Value': dbus.Array(bl, 'y')}, [])

    def ReadValue(self):
        rospy.logdebug('Person Position read: ' + repr(self.orientation))
        return dbus.Array(self.point_to_polar_bytelist(), signature='y')

    def StartNotify(self):
        if self.notifying:
            rospy.logdebug('Already notifying, nothing to do')
        else:
            self.notifying = True
            self.notify_person_position()

    def StopNotify(self):
        if self.notifying:
            self.notifying = False
        else:
            rospy.logdebug('Not notifying, nothing to do')

# The Interaction Service
class InteractionService(GattServer.Service):
    INTERACTION_UUID = 'dcaa40f9-aa61-4ee7-b1ea-875e11a0832d'

    def __init__(self, bus, index):
        super(InteractionService, self).__init__(bus, index, self.INTERACTION_UUID, True)
        self.add_characteristic(InteractionProbabilityCharacteristic(bus, 0, self))
        self.add_characteristic(InteractionModeCharacteristic(bus, 1, self))


class InteractionProbabilityCharacteristic(GattServer.Characteristic):
    INTERACTION_PROB_UUID = 'a01132e2-ef2b-45aa-8ad3-91a941624e26'

    def __init__(self, bus, index, service):
        super(InteractionProbabilityCharacteristic, self).__init__(
                bus, index,
                self.INTERACTION_PROB_UUID,
                ['read', 'notify'],
                service)
        self.notifying = False
        self.prob_lvl = 0

    def notify_probability_level(self):
        if not self.notifying:
            return
        self.PropertiesChanged(
                GattServer.GATT_CHRC_IFACE,
                { 'Value': [dbus.Byte(self.prob_lvl)] }, [])

    def level_cb(self, data):
        int_percentage = int(data.percentage)
        if self.prob_lvl != int_percentage:
            rospy.logdebug('Updated interaction probability level to %d', int_percentage)
            self.prob_lvl = int_percentage
            self.notify_probability_level()
        return

    def ReadValue(self):
        rospy.logdebug('Interaction probability level read: ' + repr(self.prob_lvl))
        return [dbus.Byte(self.prob_lvl)]

    def StartNotify(self):
        if self.notifying:
            rospy.logdebug('Already notifying, nothing to do')
            return
        self.notifying = True
        self.notify_probability_level()

    def StopNotify(self):
        if not self.notifying:
            rospy.logdebug('Not notifying, nothing to do')
            return
        self.notifying = False

class InteractionModeCharacteristic(GattServer.Characteristic):
    INTERACTION_MODE_UUID = 'dc2ecad2-7b92-4cda-85c6-da190ce82f61'

    def __init__(self, bus, index, service):
        super(InteractionModeCharacteristic, self).__init__(
                bus, index,
                self.INTERACTION_MODE_UUID,
                ['write', 'read', 'notify'],
                service)
        self.notifying = False
        self.interaction_mode = False

    def notify_interaction_mode(self):
        if not self.notifying:
            return
        self.PropertiesChanged(
                GattServer.GATT_CHRC_IFACE,
                { 'Value': [dbus.Boolean(self.interaction_mode)] }, [])

    def mode_cb(self, msg):
        self.WriteValue(msg.data)
        return

    def ReadValue(self):
        rospy.logdebug('Interaction mode read: ' + repr(self.interaction_mode))
        return [dbus.Boolean(self.interaction_mode)]

    def WriteValue(self, value):
        new_mode = bool(value)
        if self.interaction_mode != new_mode:
            self.interaction_mode = new_mode
            rospy.logdebug('Interaction mode set to: ' + repr(new_mode))
            self.notify_interaction_mode()
        return

    def StartNotify(self):
        if self.notifying:
            rospy.logdebug('Already notifying, nothing to do')
            return
        self.notifying = True
        self.notify_interaction_mode()

    def StopNotify(self):
        if not self.notifying:
            rospy.logdebug('Not notifying, nothing to do')
            return
        self.notifying = False

def register_service_cb():
    rospy.logdebug('GATT service registered')

def register_service_error_cb(error):
    rospy.logerr('Failed to register service: ' + str(error))
    rospy.signal_shutdown('Could not start Bluetooth service.')

def register_ad_cb():
    rospy.logdebug('Advertisement registered')

def register_ad_error_cb(error):
    rospy.logerr('Failed to register advertisement: ' + str(error))
    rospy.signal_shutdown('Could not advertise Bluetooth service.')

def bytelist_from_int(number, num_bytes):
    # Make sure it is an integer
    number = int(number)
    # Construct the list by shifting one byte at a time.
    return [(number>>(8*i))&0xff for i in range(num_bytes-1,-1,-1)]

def main():
    # Initialize node to get access to ROS logging.
    rospy.init_node('ble_interface_battery', log_level=rospy.DEBUG)

    # Construct the event loop. Usually, we would use ROS' spin function.
    # but the dbus library needs to use the GObject.MainLoop. Luckily, this
    # works fine with rospy.
    mainloop = gobject.MainLoop()
    gobject.threads_init()
    rospy.on_shutdown(mainloop.quit)
    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

    bus = dbus.SystemBus()

    # Advertize BLE services
    adapter = BleAdvertisement.find_adapter(bus)
    if not adapter:
        rospy.logerr('LEAdvertisingManager1 interface not found')
        return
    adapter_props = dbus.Interface(bus.get_object(BleAdvertisement.BLUEZ_SERVICE_NAME, adapter),
                                   "org.freedesktop.DBus.Properties");
    adapter_props.Set("org.bluez.Adapter1", "Powered", dbus.Boolean(1))
    ad_manager = dbus.Interface(bus.get_object(BleAdvertisement.BLUEZ_SERVICE_NAME, adapter),
                                BleAdvertisement.LE_ADVERTISING_MANAGER_IFACE)
    robot_advertisement = RobotAdvertisement(bus, 0)
    ad_manager.RegisterAdvertisement(robot_advertisement.get_path(), {},
                                     reply_handler=register_ad_cb,
                                     error_handler=register_ad_error_cb)

    # Put the services on the Dbus for Bluez to handle them.
    service_manager = dbus.Interface(bus.get_object(GattServer.BLUEZ_SERVICE_NAME,
                                                    adapter),
                                     GattServer.GATT_MANAGER_IFACE)

    bat_service = BatteryService(bus, 1)
    service_manager.RegisterService(bat_service.get_path(), {},
                                    reply_handler=register_service_cb,
                                    error_handler=register_service_error_cb)

    odom_service = OdometryService(bus, 2)
    service_manager.RegisterService(odom_service.get_path(), {},
                                    reply_handler=register_service_cb,
                                    error_handler=register_service_error_cb)

    people_service = PeopleService(bus, 3)
    service_manager.RegisterService(people_service.get_path(), {},
                                    reply_handler=register_service_cb,
                                    error_handler=register_service_error_cb)

    interaction_service = InteractionService(bus, 4)
    service_manager.RegisterService(interaction_service.get_path(), {},
                                    reply_handler=register_service_cb,
                                    error_handler=register_service_error_cb)

    # Populate ROS Node
    laptop_charge_sub = rospy.Subscriber('/laptop_charge',
                                         BatteryState,
                                         bat_service.characteristics[0].level_cb)
    odometry_sub = rospy.Subscriber('/odom',
                                    Odometry,
                                    odom_service.characteristics[0].position_cb)
    odometry_sub.impl.add_callback(odom_service.characteristics[1].orientation_cb,
                                   None)
    people_sub = rospy.Subscriber('/people_tracker_measurements',
                                  PositionMeasurementArray,
                                  people_service.person_position_array_cb)
    interaction_prob_sub = rospy.Subscriber('/interaction_probability',
                                            Float32,
                                            interaction_service.characteristics[0].level_cb)
    interaction_mode_service = rospy.Service('set_interaction_mode',
                                             SetBool,
                                             interaction_service.characteristics[1].mode_cb)

    mainloop.run()

if __name__ == '__main__':
    main()
